StandBy/Models/Agenda.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StandBy.Models
{
    public class Agenda
    {
        [Key] public int Id { get; set; }

        [Required] [Range(0, double.MaxValue)] public double ValorBruto { get; set; }

        [Range(0, double.MaxValue)] public double ValorLiquido { get; set; }

        [Range(0, float.MaxValue)] public float Taxa { get; set; }

        [Required] [DataType(DataType.Date)] public DateTime Liquidacao { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(50)]
        public string Titulo { get; set; }

        public int ClienteId { get; set; }

        public Cliente Cliente { get; set; }
    }
}

StandBy/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StandBy.Models
{
    public class Cliente
    {
        [Key] public int Id { get; set; }

        [Required]
        [MinLength(14)]
        [MaxLength(14)]
        public string Cnpj { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(50)]
        public string RazaoSocial { get; set; }

        [Required] [DataType(DataType.Date)] public DateTime Fundacao { get; set; }

        [Required] [Range(0, double.MaxValue)] public double Capital { get; set; }

        [Required] [MaxLength(1)] public char Classificacao { get; set; }

        [Required] public bool Quarentena { get; set; }

        [Required] public bool Status { get; set; }

        public List<Agenda> Agendas { get; set; }
    }
}

StandBy/Models/ErrorViewModel.cs
namespace StandBy.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StandBy/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace StandBy.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Lista()
        {
            return View();
        }
    }
}

StandBy/Controllers/PrincipalController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using StandBy.Models;

namespace StandBy.Controllers
{
    public class PrincipalController : Controller
    {
        public IActionResult Inicio()
        {
            return View();
        }

        public IActionResult Privacidade()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult _Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

StandBy/Views/Cliente/Cadastro.cshtml
@{
    ViewData["Titulo"] = "Registro de cliente";
    const string feedback = "Favor preencher o campo";
}

<div class="container my-4">
    <div class="row align-items-center pagina">
        <div class="col col-12 mx-auto align-self-start">
            <p class="h5 text-center mb-4">Dados da empresa</p>
        </div>
        <div class="col col-12">
            <form asp-action="" asp-antiforgery="true" method="post"
                  id="formulario-cadastro" class="was-validated" novalidate data-ajax="true"
                  data-ajax-method="POST" data-ajax-complete="ValidarCadastro">
                <div class="form-row justify-content-center">
                    <div class="form-group col col-10 col-md-3">
                        <label for="cnpj" class="mb-1">CNPJ</label>
                        <input id="cnpj" type="text" name="Cnpj" class="form-control cnpj"
                               minlength="18" placeholder="Informe o CNPJ do cliente" required
                               onkeyup="ValidarPreenchimento($('#submit-cliente'))" />
                        <div id="feedback-cnpj" class="invalid-feedback">Informe um CNPJ válido</div>
                    </div>
                    <div class="form-group col col-10 col-md-3">
                        <label for="razao-social" class="mb-1">Razão social</label>
                        <input id="razao-social" type="text" name="RazaoSocial" class="form-control"
                               placeholder="Informe a razão social do cliente" minlength="5" maxlength="50" required
                               onkeyup="ValidarPreenchimento($('#submit-cliente'))" />
                        <div class="invalid-feedback">@feedback</div>
                    </div>
                    <div class="form-group col col-10 col-md-2">
                        <label for="status" class="mb-1">Status</label>
                        <select id="status" name="Status" class="selectpicker show-tick"
                                data-width="100%" data-container="body" data-style="text-capitalize" required
                                data-title="Selecionar Status" onchange="ValidarPreenchimento($('#submit-cliente'))">
                            <option value="1" class="text-capitalize">
                                Status exemplo
                            </option>
                            
                            @* @foreach (var (chave, valor) in Global.ListarSituacao(3, 4)) *@
                            @* { *@
                            @*     <option value="@chave"> *@
                            @*         @valor *@
                            @*     </option> *@
                            @* } *@
                                                            
                        </select>
                    </div>
                </div>
                <div class="form-row justify-content-center mb-4">
                    <div class="form-group col col-10 col-md-2">
                        <label for="capital" class="mb-1">Capital</label>
                        <input id="capital" type="text" name="Capital" class="form-control moeda"
                               placeholder="00.000,00" required
                               onkeyup="ValidarPreenchimento($('#submit-cliente'))" />
                        <div class="invalid-feedback">@feedback</div>
                    </div>
                    <div class="form-group col col-10 col-md-2">
                        <label for="quarentena" class="mb-1">Quarentena</label>
                        <select id="quarentena" name="Quarentena" class="selectpicker show-tick"
                                data-width="100%" data-container="body" data-style="text-capitalize" required
                                data-title="Selecionar Opção" onchange="ValidarPreenchimento($('#submit-cliente'))">
                            <option value="0" class="text-capitalize">
                                Não
                            </option>
                            <option value="1" class="text-capitalize">
                                Sim
                            </option>
                        </select>
                    </div>
                    <div class="form-group col col-10 col-md-2">
                        <label for="classificacao" class="mb-1">Classificação</label>
                        <select id="classificacao" name="Classificacao" class="selectpicker show-tick"
                                data-width="100%" data-container="body" data-style="text-capitalize" required
                                data-title="Selecionar Opção" onchange="ValidarPreenchimento($('#submit-cliente'))">
                            <option value="1" class="text-capitalize">
                                Classificação exemplo
                            </option>                
                        </select>
                    </div>
                    <div class="form-group col col-10 col-md-2">
                        <label for="fundacao" class="mb-1">Data de fundação</label>
                        <input id="fundacao" name="DataTemporaria" type="text" class="form-control date data"
                               placeholder="00/00/0000" minlength="10" required
                               onchange="ValidarPreenchimento($('#submit-cliente'))" />
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col col-10 col-md-4">
                        <button id="submit-cliente" class="btn btn-success btn-block" type="submit">
                            Finalizar registro
                        </button>
                    </div>
                </div>
            </form>
            <div class="row justify-content-center">
                <div class="col col-10 col-md-4 mx-auto align-self-end">
                    @* <a class="btn btn-danger btn-block" href="@Url.Action("Lista", "Empresa")"> *@
                    @*     Retornar *@
                    @* </a> *@
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="~/js/Cliente/cliente.js" type="text/javascript"></script>
<script src="~/js/Cliente/cadastro.js" type="text/javascript"></script>

StandBy/Views/Cliente/Lista.cshtml
@{
    ViewData["Titulo"] = "Lista de clientes";
}

<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col col-12">
            <p class="h5 text-center">@ViewData["Titulo"]</p>
        </div>
    </div>
    <div class="row justify-content-between mb-3 mb-md-0">
        <div class="col col-5 col-sm-4 col-md-3 col-lg-2">
            <a class="text-info" href="#">
                <small>Filtrar lista</small>
            </a>
        </div>
        <div class="col col-7 col-sm-4 col-md-3 col-lg-2">
            <a href="@Url.Action("Cadastro")" class="btn btn-success btn-block" target="_blank">
                Novo registro
            </a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col col-12">
            <div class="cep d-none"></div>
            <table id="tabela-cliente" class="table table-hover table-bordered w-100">
                <thead class="text-center bg-info text-light">
                <tr>
                    <th>CNPJ</th>
                    <th>Razão social</th>
                    <th>Fundação</th>
                    <th>Capital</th>
                    <th>Classificação</th>
                    <th>Quarentena</th>
                    <th>Status</th>
                    @* <th>Ações</th> *@
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="align-middle cnpj">12345678901234</td>
                    <td class="align-middle text-capitalize" style="width: 35%;">exemplo de razão social</td>
                    <td class="align-middle data">05052000</td>
                    <td class="align-middle moeda">10000</td>
                    <td class="align-middle">A</td>
                    <td class="align-middle">NÃO</td>
                    <td class="align-middle">ATIVA</td>
                    @* <td style="width:5%;"> *@
                    @*     <div class="btn-group btn-block" role="group" aria-label="Grupo de ações para acompanhamento"> *@
                    @*         <a href="@Url.Action("Detalhamento", "Empresa", new {idEmpresa = empresa.IdEmpresa})" *@
                    @*            class="btn btn-sm btn-outline-info" role="button" *@
                    @*            data-ajax="true" data-ajax-method="POST" data-ajax-complete="Detalhamento"> *@
                    @*             <i class="fas fa-info-circle"></i> *@
                    @*         </a> *@
                    @*         <a class="btn btn-sm btn-outline-info" role="button" target="_blank" *@
                    @*            href="@Url.Action("Lista", "Observacao", new {entidade = 4, objeto = empresa.IdEmpresa})"> *@
                    @*             <i class="fas fa-comment"></i> *@
                    @*         </a> *@
                    @*     </div> *@
                    @* *@
                    @*     @if (Validacao.ValidarPerfil(new List<byte> {1, 2, 5}) && Validacao.ValidarPermissao()) *@
                    @*     { *@
                    @*         <div class="btn-group btn-block" role="group" aria-label="Grupo de ações para gerenciamento"> *@
                    @*             <a href="@Url.Action("Gerenciamento", "Empresa", new {idEmpresa = empresa.IdEmpresa})" *@
                    @*                class="btn btn-sm btn-outline-danger" role="button" target="_blank"> *@
                    @*                 <i class="fas fa-pen"></i> *@
                    @*             </a> *@
                    @*             <a href="#" class="btn btn-sm btn-outline-danger" *@
                    @*                data-toggle="modal" data-target="#modal-inativacao" role="button" *@
                    @*                onclick="ValidarInativacao('@empresa.IdEmpresa', '@empresa.NomeFantasia.ToLower()')"> *@
                    @*                 <i class="fas fa-times"></i> *@
                    @*             </a> *@
                    @*         </div> *@
                    @*     } *@
                    @* *@
                    @* </td> *@
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal" id="modal-inativacao" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Atenção</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="confirmacao"></p>
            </div>
            <form asp-action="" asp-antiforgery="true" method="post"
                  id="formulario-inativacao" data-ajax="true" data-ajax-method="POST"
                  data-ajax-complete="FinalizarInativacao">
                <input type="hidden" id="id-empresa" name="idEmpresa"/>
                <div class="modal-footer">
                    <button id="cancela-inativacao" type="button" class="btn btn-success" data-dismiss="modal">
                        Voltar
                    </button>
                    <button id="submit-inativacao" type="submit" class="btn btn-danger">
                        Excluir
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="~/js/Cliente/cliente.js" type="text/javascript"></script>
<script src="~/js/Cliente/lista.js" type="text/javascript"></script>

StandBy/Views/Principal/Inicio.cshtml
@{
    ViewData["Titulo"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StandBy/Views/Principal/Privacidade.cshtml
@{
    ViewData["Titulo"] = "Políticas de privacidade";
}
<h1>@ViewData["Titulo"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

StandBy/Views/Shared/_Error.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

StandBy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Titulo"] - Stand</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-select.css"/>
    <link rel="stylesheet" href="~/lib/datepicker/css/bootstrap-datepicker.min.css"/>
    <link rel="stylesheet" href="~/lib/toast/css/iziToast.css"/>
    <link rel="stylesheet" href="~/lib/datatable/css/datatables.css"/>
    <link rel="stylesheet" href="~/lib/datatable/css/buttons.datatables.css"/>
    <link rel="stylesheet" href="~/css/Shared/layout.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Principal" asp-action="Inicio">Stand</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Principal" asp-action="Inicio">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Lista">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Principal" asp-action="Privacidade">Sobre</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.UtcNow.Year - Stand - <a asp-area="" asp-controller="Principal" asp-action="Privacidade">Privacidade</a>
    </div>
</footer>
<script src="~/lib/jquery-mask/jquery.mask.js" type="text/javascript"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap-select.js" type="text/javascript"></script>
<script src="~/lib/datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="~/lib/datepicker/locales/bootstrap-datepicker.pt-BR.min.js" type="text/javascript"></script>
<script src="~/lib/toast/js/iziToast.js" type="text/javascript"></script>
<script src="~/lib/datatable/js/datatables.js" type="text/javascript"></script>
<script src="~/lib/datatable/js/datatables.buttons.js" type="text/javascript"></script>
<script src="~/js/Shared/layout.js" type="text/javascript" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>